### PR TITLE
Update dependency to parent 5.4.0 SNAPSHOT

### PR DESCRIPTION
**Pull request by szaluzhskiy**

### CODE REVIEW

**Comment by DavideD** [comment]
Thanks @szaluzhskiy,
 this is not enough though.

When working on this issue you also need to make sure that the project builds.
In this case something has changed in `IgniteSqlQueryParser` and it doesn't compile anymore.

Also, @schernolyas can you have a look at this and maybe help him? Thanks

**Comment by DavideD** [comment]
ok to test

**Comment by schernolyas** [comment]
HI @DavideD !

Yes, of course!

**Comment by szaluzhskiy** [comment]
This update should be suspended until 5.4 of hibernate-ogm released

**Comment by DavideD** [comment]
> This update should be suspended until 5.4 of hibernate-ogm released

Not really, the way we work is to keep the snapshot version on master, this way when we apply some changes on OGM we can check if they cause troubles with Ignite.

We could wait for the realease of OGM 5.4 but if we can be more pro-active about it, that's better.

We already deploy a snapshot every night, maybe you don't have it because the JBoss repository is not in your maven configuration?
Just make sure to add the -s option when you build the project:

`mvn install -s settings-example.xml `

**Comment by DavideD** [comment]
I'm going to close this PR for now, feel free to re-open it when the project builds or create a new one.

Cheers

**Pull request closed without merging**
