### PR TITLE
JBOss modules + Integretaion tests + updates

### PR DESCRIPTION
**Pull request by DavideD**
@schernolyas Could you have a look at this PR and see if it makes sense? I basically rebased cleaned-up and updated the previous one.

THanks

### CODE REVIEW

**Comment by schernolyas** [comment]
Hi @DavideD !

Okey. I will review.

**Comment by schernolyas** [comment]
@DavideD Can I update to 5.3.1.Final ?

**Comment by DavideD** [comment]
Nope, that's done during the release

**Comment by schernolyas** [comment]
I have reviewed. 
I sent PR (https://github.com/DavideD/hibernate-ogm-ignite/pull/2 ) to your branch. Merge it, if it needs.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-ogm-ignite/pull/16

THanks

**Pull request merged**
